version: "3.7"

services:
  backend:
    container_name: backend
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:5000"
    networks:
      - app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fleet_management
    ports:
      - "5432:5432"
    