version: "3.7"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "9000:5000"
    networks:
      - app
    restart: unless-stopped
    depends_on:
      - postgres
    command: >
      sh -c "until pg_isready -h postgres -p 5432; do sleep 1; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:9000"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: fleet_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  app:
    driver: bridge

volumes:
  postgres_data:
    driver: local
