version: "3.7"

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app
    env_file: .env
    restart: unless-stopped
    depends_on:
<<<<<<< Updated upstream
      - postgres
=======
      postgres:
        condition: service_healthy
>>>>>>> Stashed changes

  postgres:
    image: postgres:latest
    container_name: database
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=fleet_management
    ports:
      - "5432:5432"
    networks:
      - app
    volumes:
      - postgres:/var/lib/postgresql/data
<<<<<<< Updated upstream
=======
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
>>>>>>> Stashed changes

volumes:
  postgres:

<<<<<<< Updated upstream
networks:
  app:
    driver: bridge
=======

networks:
  app:
    driver: bridge
>>>>>>> Stashed changes
