# Generated by Django 5.0.3 on 2024-04-11 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vehicles', '0001_initial'),
        ('missions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.vehicle'),
        ),
        migrations.AddField(
            model_name='mission',
            name='requester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driver',
            name='mission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missionparticipant',
            name='mission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission'),
        ),
        migrations.AddField(
            model_name='missionparticipant',
            name='participant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('mission_id', 'vehicle_id')},
        ),
        migrations.AlterUniqueTogether(
            name='missionparticipant',
            unique_together={('mission_id', 'participant_id')},
        ),
    ]
