# Generated by Django 5.0.3 on 2024-03-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together={('mission_id', 'vehicle_id')},
        ),
    ]
