# Generated by Django 4.2.6 on 2024-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.CharField(choices=[('1', 'On Going'), ('2', 'Arrived'), ('3', 'OverDue'), ('4', 'Pending'), ('5', 'Approved'), ('6', 'Rejected')], default='4', max_length=20),
        ),
        migrations.AlterField(
            model_name='mission',
            name='title',
            field=models.CharField(default='asmae', max_length=100),
        ),
    ]
