# Generated by Django 5.0.3 on 2024-03-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('role_id', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
