# Generated by Django 5.0.3 on 2024-03-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_delete_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_id',
        ),
    ]
