# Generated by Django 4.2.6 on 2024-03-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('dname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('role_id', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('vehicle_id', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.IntegerField()),
                ('m_type', models.CharField(max_length=20)),
                ('decription', models.CharField(max_length=20)),
                ('cost', models.IntegerField()),
                ('kms', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=20)),
                ('make', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('Vtype', models.CharField(max_length=20)),
                ('kms', models.CharField(max_length=20)),
                ('notification_time', models.CharField(max_length=20)),
                ('notification_mileage', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
            ],
        ),
    ]
