# Generated by Django 5.0.4 on 2024-04-23 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('vehicle_id', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('cost', models.FloatField()),
                ('kms', models.FloatField()),
                ('m_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.mtype')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'maintenance'), ('2', 'available'), ('3', 'booked')], default='2', max_length=10)),
                ('kms', models.FloatField()),
                ('notification_time_year', models.IntegerField()),
                ('notification_mileage', models.FloatField()),
                ('picture', models.ImageField(null=True, upload_to='vehicle_pictures/')),
                ('Vtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.vtype')),
            ],
        ),
    ]
