# Generated by Django 4.2.5 on 2024-03-31 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[(1, 'maintenance'), (2, 'available'), (3, 'booked')], default=2)),
                ('kms', models.CharField(max_length=20)),
                ('notification_time_year', models.IntegerField()),
                ('notification_mileage', models.FloatField()),
                ('Vtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.vtype')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('vehicle_id', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.IntegerField()),
                ('decription', models.CharField(max_length=500)),
                ('cost', models.FloatField()),
                ('kms', models.FloatField(max_length=20)),
                ('m_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vehicles.mtype')),
            ],
        ),
    ]
