# Generated by Django 5.0.3 on 2024-03-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mtype',
            name='record_id',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_id',
        ),
        migrations.RemoveField(
            model_name='vtype',
            name='type_id',
        ),
    ]
