# Generated by Django 5.0.3 on 2024-03-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='title',
            field=models.CharField(default='default title', max_length=20),
            preserve_default=False,
        ),
    ]
