# Generated by Django 4.2.6 on 2024-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0002_remove_maintenance_vehicle_id_maintenance_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='Vtype',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('1', 'maintenance'), ('2', 'available'), ('3', 'booked')], default='2', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vtype',
            field=models.CharField(choices=[('1', 'maintenance'), ('2', 'available'), ('3', 'booked')], default='2', max_length=20),
        ),
    ]
