# Generated by Django 5.0.4 on 2024-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0002_remove_maintenance_vehicle_id_maintenance_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('1', 'maintenance'), ('2', 'available'), ('3', 'booked')], default='2', max_length=20),
        ),
    ]
