# Generated by Django 4.2.6 on 2024-05-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0003_remove_vehicle_vtype_alter_vehicle_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vtype',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tool',
            field=models.CharField(choices=[('1', 'Car'), ('2', 'Bus'), ('3', 'Taxi')], default='2', max_length=20),
        ),
    ]
