# Generated by Django 4.2.6 on 2024-05-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vehicles', '0004_remove_vehicle_vtype_vehicle_tool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='tool',
            field=models.CharField(max_length=20),
        ),
    ]
