name: Django CI



on:
  push:
    branches: '**'
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: Run Tests
        run: |
          python ./backend/manage.py test ./backend/apps/missions --settings=./backend/Municipality_fleet_management.ci_settings
