name: Django CI

on:
  push:
    branches: [Douae]

jobs:

  build:
    runs-on: ubuntu-20.04

    container: python:3.8

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432


    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt
      - name: List backend directory
        run: |
          ls -la ./backend/
      - name: Run Tests
        run: |
          python ./backend/manage.py test apps/missions
        env:
          DATABASE_NAME: postgres
          DATABASE_USER: postgres
          DATABASE_PASS: postgres
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432
