name: Django CI

on:
  push:
    branches: '**'
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: List files in the root directory
        run: ls -l
      - name: Change directory and list files
        run: |
          cd Municipality_Fleet_Management
          ls -l
      - name: Build container
        run: |
          cd Municipality_Fleet_Management
          docker-compose up -d --build
      - name: Migrations
        run: |
          docker-compose exec backend python manage.py makemigrations
          docker-compose exec backend python manage.py migrate
      - name: Run Tests
        run: |
          docker-compose exec backend python manage.py test apps/missions