name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          script: |
            cd Municipality_Fleet_Management
            echo "Changing branch to main"
            git checkout main
            echo "Stashing any existing changes"
            git stash
            echo "Pulling latest API changes"
            git pull
            chmod +rwx deploy.sh
            ./deploy.sh

