name: Deploy

on:
  push:
    branches:
      - Douae

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          script: |
            git clone https://github.com/Agile-Fleet-Management/Municipality_Fleet_Management.git
            pwd
            ls
            cd ./Municipality_Fleet_Management
            ./scripts/deploy.sh
