name: Deploy

on:
  workflow_run:
    workflows: ["Django CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          script: |
            cd Municipality_Fleet_Management
            echo "Pulling latest API changes"
            echo "Stashing any local changes..."
            git stash --include-untracked
            git pull
            chmod +rwx ./scripts/deploy.sh
            ./scripts/deploy.sh

