name: Deploy

on:
  push:
    branches:
      - Douae

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          script: |
            #!/bin/bash

            echo "Pulling latest API changes"
            
            git pull
            
            echo "Building latest changes"
            
            docker-compose up -d --build
            
            echo "Deployment complete"
