name: Deploy

on:
  push:
    branches:
<<<<<<< Updated upstream
      - main
=======
      - Douae
>>>>>>> Stashed changes

jobs:
  deploy:
    name: Deploy
<<<<<<< Updated upstream
    runs-on: ubuntu-22.04
=======
    runs-on: ubuntu-latest
>>>>>>> Stashed changes
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_DROPLET_IP }}
          username: ${{ secrets.DIGITALOCEAN_DROPLET_USERNAME }}
          password: ${{ secrets.DIGITALOCEAN_DROPLET_PASSWORD }}
          script: |
            cd Municipality_Fleet_Management
<<<<<<< Updated upstream
            ./scripts/deploy.sh 
=======
            ./scripts/deploy.sh

>>>>>>> Stashed changes
